pplace:
  port: 8080
  version: "0.0-dev"
  sheet:
    width: 500
    height: 500
    place_cooldown: 5000
  database:
    host: "https://example.com/"
    port: 5432
    user: "user"
    password: "pass"
    dbname: "pplace"
  jwt:
    secret: "code"
    expiration: 720